### ISSUE TITLE
Extend usability of Write-HostPrompt

### ISSUE THREAD

**Issue by GraphiteWingedBird** [jasoth/MSIdentityTools#1]
I happened upon your `Write-HostPrompt` script while trying to find an easier way to create a PowerShell menu, and I have been using it quite a bit ever since! So first off I want to say thank you - it helped me to keep from inventing the wheel from scratch and it has been an awesome addition to my scripts.

Secondly, I've made some updates that I wanted to share in case you use `Write-HostPrompt` somewhat often and might feel like the syntax is a bit verbose. Since I primarily only use Choices, I'll probably set that `ParameterSet` as my default, or remove the `$Fields` option entirely, but for flexibility I haven't removed it yet, but I also haven't tried to optimize it at all since I don't really have a use case.

Basic summary of big changes:

- I've changed `$Choices` to a type of `[string[]]` so that you don't need to create a ton of new `[System.Management.Automation.Host.ChoiceDescription]` objects during the function call
- `$Choices` are now expected to be a single string per choice with a semi-colon separating the choice `Label` and choice `Message`
- Pretty cool bit just added, `$i = 1` as a counter in the `begin` block and incrementing it as each `$Choice` is added to `$listChoices`. The neat thing here is that if a choice doesn't contain a hot key/keyboard accelerator (i.e. there's no `&` in the Label) then that choice will get assigned the current number of the counter. This probably wigs out for 10+ choices, but people shouldn't provide that many choices!

Smaller changes:

- Added some examples using the new syntax, as well as an example of splatting that I use quite often in longer scripts where readability is important
- Changed `$Caption` to `$Title` because I kept messing it up and to me it is a title. I'm not going to fight Microsoft on their usage of caption vs. title, but title is better for me!
- Changed the `$DefaultChoice` to be `0` instead of `-1`

```powershell
<#
.SYNOPSIS
    Displays a PowerShell prompt for multiple fields or multiple choices.
.DESCRIPTION
    Displays a PowerShell prompt for multiple fields or multiple choices.
.EXAMPLE
    PS C:\>Write-HostPrompt "Prompt Caption" "Prompt Message" -Fields @(
        New-Object System.Management.Automation.Host.FieldDescription -ArgumentList "Field 1"
        New-Object System.Management.Automation.Host.FieldDescription -ArgumentList "Field 2"
    )
    Display prompt for 2 fields.
.EXAMPLE
    PS C:\>Write-HostPrompt "Prompt Caption" "Prompt Message" -DefaultChoice 0 -Choices @(
		"Choice &1 Label; Choice 1 Help Message"
        "&Yes; Yes Help Message"
        "&No; No Help Message"
    )
    Display prompt with 3 choices using an explicit (and easy to read) array for Choices
.EXAMPLE
	PS C:\>Write-HostPrompt "Prompt Caption" "Prompt Message" -DefaultChoice 0 -Choices "&First;First Help","&Second;Second Help","&Third;Third Help"
	There are a number of alternative entry methods such as storing the choices in a variable and/or using the pipeline
.EXAMPLE
	PS C:\>$HostPromptArguments = @{
				Title = "Prompt Caption"
				Message = "Prompt Message"
				Choices = @(
					"First Choice; First help message"
					"Second Choice; Second help message"
					"Third Choice; Third help message"
				)
				DefaultChoice = 0
			}
	PS C:\>Write-HostPrompt @HostPromptArguments
	Another great method is splatting some or all of the arguments using a hash table
.INPUTS
    System.Management.Automation.Host.FieldDescription
    System.Management.Automation.Host.ChoiceDescription
.OUTPUTS
    System.Collections.Generic.Dictionary[System.String,System.Management.Automation.PSObject]
    System.Int32
#>
function Write-HostPrompt {
    [CmdletBinding()]
    param
    (
        # Caption to preceed or title the prompt.
        [Parameter(Mandatory=$true, Position=1)]
        [string] $Title,
        # A message that describes the prompt.
        [Parameter(Mandatory=$true, Position=2)]
        [string] $Message,
        # The fields in the prompt.
        [Parameter(Mandatory=$true, ParameterSetName='Fields', Position=3, ValueFromPipeline=$true)]
        [System.Management.Automation.Host.FieldDescription[]] $Fields,
        # The choices the shown in the prompt.
        [Parameter(Mandatory=$true, ParameterSetName='Choices', Position=3, ValueFromPipeline=$true)]
        [string[]] $Choices,
        # The index of the label in the choices to make default.
        [Parameter(Mandatory=$false, ParameterSetName='Choices', Position=4)]
        [int] $DefaultChoice = 0
    )

    begin {
        ## Create list to capture multiple fields or multiple choices.
        [System.Collections.Generic.List[System.Management.Automation.Host.FieldDescription]] $listFields = New-Object System.Collections.Generic.List[System.Management.Automation.Host.FieldDescription]
        [System.Collections.Generic.List[System.Management.Automation.Host.ChoiceDescription]] $listChoices = New-Object System.Collections.Generic.List[System.Management.Automation.Host.ChoiceDescription]
		$i = 1
    }

    process {
        switch ($PSCmdlet.ParameterSetName) {
            'Fields' {
                foreach ($Field in $Fields) { $listFields.Add($Field) }
            }
            'Choices' {
                foreach ($Choice in $Choices) { 
					$Label, $HelpMessage = $Choice.Split(';').Trim()
					If ($Label -notmatch '&'){
						$Label = $Label+"&$i`b"
					}
					$Choice = [System.Management.Automation.Host.ChoiceDescription]::new($Label, $HelpMessage)
					$listChoices.Add($Choice)
					$i++
				}
            }
        }
    }

    end {
        switch ($PSCmdlet.ParameterSetName) {
            'Fields' { return $Host.UI.Prompt($Title,$Message,$listFields.ToArray()) }
            'Choices' { return $Host.UI.PromptForChoice($Title,$Message,$listChoices.ToArray(),$DefaultChoice) }
        }
    }
}
```

**Comment by GraphiteWingedBird** [comment]
I also looked into using fields a little bit, although the use case for me is still pretty small (and the syntax for simply calling `$host.UI.Prompt` isn't too bad) - however, there doesn't seem to be a need to define your `$Fields` parameter as `[System.Management.Automation.Host.FieldDescription[]] $Fields` instead of `[string[]] $Fields`. That simple change will let you call something like:
```powershell
Write-HostPrompt "Prompt Caption" "Prompt Message" -Fields @(
"Field 1"
"Field 2"
)
```

**Comment by jasoth** [comment]
Hi @GraphiteWingedBird,
I'm glad you found this function helpful. The intent was to leave it as flexible as possible and since it will primarily be used in scripts, I am not too concerned with the long definition of Choices and Fields. However, I think some of the simplicity you are looking for already works with the current parameter types. For example:
`Write-HostPrompt "Prompt Caption" -Fields "Field 1", "Field 2"`
or even
`Write-HostPrompt "Prompt Caption" -Choices "Choice &1", "Choice &2"`

I have never really put much time into this function but you inspired me to give it a little more love by adding HelpMessages and NumberedHotKeys parameters based on your suggestions here. Obviously, you are welcome to adjust to better meet your needs.
I actually manage the latest version of that function here:
https://github.com/jasoth/Utility.PS/blob/master/src/Write-HostPrompt.ps1
